server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      #      最大支持文件大小
      max-file-size: 20MB
      #      最大支持请求大小
      max-request-size: 20MB
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false

filepath: D:/file/
